name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Install dependencies
      run: poetry install --no-interaction
    
    - name: Test FastAPI application can start
      run: |
        # Set mock environment variables for testing
        export LLM_MODEL="test-model"
        export GROQ_API_KEY="test-key"
        # Test that the app can import without errors
        poetry run python -c "from src.service_host.main import app; print('✅ FastAPI app loads successfully')"
      env:
        LLM_MODEL: "test-model"
        GROQ_API_KEY: "test-key"
    
    - name: Build package
      run: poetry build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/